language: python
python:
- 3.7
- 3.6
- 3.5
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: johnnygreco
  password:
    secure: C+Q/jXZLaIu7NtE/hyYN0C4ShkR3m1Bx+R1kXIOYsDmO+Kpy4QqLwkT+gXhGad/xVXuoF5vAEEHfbs4FActlhj46kO+7MN5ai0jPp+K68tOxvNQhBr43FuBycfiQKk6Bdxt+RUPKcKc/Ros0hqqR9WS4d2uNhtzgd4cP3IXUtb446DXQlCUqzWfwNn4ybsOrXMXOjC4DsHz6Oz73p4xhypfZneFfm+hYEbYhMEALlitloaK/gDc4kD/PNuesnu4RpiKYb7kfIa9kMbzCuvSSB9Bv48PHnaLDEQnvXVkjseitUpiG1tmPQVSnbEm8hxsRCeYyQxRIPapbzMmigoy6UOOP3TgtXEX8nlWPRXVsUnWH8hIouku5gj+BGniqMGdWWM8bm4QseBadlVKFG4COd1jPoXM09ZTAIS+feNoqxVqspjocoamAwKm8iSaOKorc4/GIA1DJVzCrwBCbBCP1A4IiKpeNeIFUuwQsv4rjBAfflHEXWpJ70p0C3bR8zp2dHg/oqe+yvyh5LcQvSLJNXCy26K5jpSAJ6RjgRLKG2FNnwYxkFJxJVRPIW4gTuzYg9Prxsc+Jogt3ccKYQvG61HVM0XMsMud8t7r0/VFQy7FzK/I/dgiMOoGZUBzgRD2niprygGZCuqHo8GOR9WU4OECV6w+gQHEHNrve1ZWJqTw=
  on:
    tags: true
    repo: johnnygreco/justsersics
    python: 3.7
